### PR TITLE
add missing schema versions

### PR DESCRIPTION
**Pull request by askainet**
- v1.11.1
- v1.12.0
- v1.12.1
- v1.12.2

### CODE REVIEW

**Comment by vblagoje** [comment]
I'd copy the contents of version 1.12.2 to  1.12.x

**Review by julian-risch — CHANGES_REQUESTED** [review]
The schema files look good to me! 👍  Just remove the `script.py` from this PR and then it's ready to be merged.

**Comment by vblagoje** [comment]
@julian-risch, what about missing PromptNode components in 1.12.0 and 1.12.1?

**Comment by julian-risch** [comment]
In the schema PromptNode is only missing from 1.12.0, which is correct because 1.12.0 didn't include the PromptNode. So that's fine.
Regarding a schema for 1.12.x: That's what's haystack-pipeline-main.schema.json is for no? If we have a 1.12.3 release in future, then we will add a schema for 1.12.3

**Comment by vblagoje** [comment]
Yes, correct @julian-risch

**Comment by askainet** [comment]
The missing schemas were generated using the official Haystack docker images for each specific version, as proposed in https://github.com/deepset-ai/haystack-json-schema/pull/2 to automate schema creation for tagged releases.

This is the script I used:
```bash
#!/bin/bash -ex

TAGS="v1.11.1 v1.12.0 v1.12.1 v1.12.2"

git clone https://github.com/askainet/haystack-json-schema.git haystack-json-schema

cat > haystack-json-schema/script.py <<EOF
import sys
import logging
from pathlib import Path

logging.basicConfig(level=logging.DEBUG)

sys.path.append(".")
from haystack.nodes._json_schema import update_json_schema

update_json_schema(destination_path=Path("/haystack-json-schema") / "json-schema")
EOF

for tag in $TAGS
do
  docker run -it -v "${PWD}/haystack-json-schema:/haystack-json-schema" "docker.io/deepset/haystack:base-cpu-${tag}" python3 /haystack-json-schema/script.py
done
```

**Review by julian-risch — APPROVED** [review]

**Pull request merged**
